version: "3.3"
services:
  node:
    build: .
    environment:
      - NODE_ENV=development
    tty: true
    command: sh -c "cd my-app && yarn start"
    volumes:
      - ./public:/usr/src/my-app/public
      - ./src:/usr/src/my-app/src
    ports:
      - "3000:3000"